# mkdocs.yml
site_name: Jonathon's Portfolio

theme:
  name: "material"
  custom_dir: "docs/portfolio-theme"
  logo: "img/logo-96px.png"
  font: 
    text: Orbitron
  palette:
    primary: 'blue'
    accent: 'blue'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css: 
- css/dark_theme.css
- css/codehilite.css
- css/profont.css
- css/youtube-videos.css
- css/nta-weekly-schedule-cards.css
- https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js


plugins:
- search
- mkdocstrings

nav:
  - Welcome (EN): index.md
  - Wilkommen (DE): index-de.md
  - Projects (EN):
    - N2 Pairs Trader: projects/n2-pairs-trader.md
    - News Trading Analyzer: projects/n2-pairs-trader.md
  - Projekte (DE):
    - N2 Pairs Trader: projects/n2-pairs-trader-de.md
    - News Trading Analyzer: projects/n2-pairs-trader-de.md
  - Contact/Kontakt (EN/DE): contact.md


edit_uri: '#docs/'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  # - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - attr_list
  - md_in_html
  # - fontawesome_markdown
